#
# BASE & PREPROD config
#

title: FIFTY-ONE International | District 104 | Luxembourg
logo: logo.png
email: admin@fiftyone.lu
description: > 
  Depuis 51 ans le soutien de projets sociaux
  à travers l'amitié, l'estime, la tolérance

baseurl: ""
url: "https://preprod.fiftyone.lu" # the base hostname & protocol for your site, e.g. http://example.com

facebook: fiftyone-district104

collections:
  events:
    output: true
    permalink: /events/:title/
  actions:
    output: true
    permalink: /actions/:title/
  clubs:
    output: true
    permalink: /clubs/:title/

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - design
  - config-forestryio.yml

deploy:
  - rsync -aze ssh --delete ./ pst@aperta.lu:/var/www/fiftyone.lu/preprod/

