---
new_page_extension: md
auto_deploy: true
admin_path: "/admin/"
webhook_url: 
sections:
- type: directory
  path: _events
  label: Events
  create: documents
  match: "**/*"
  templates:
  - minimaster-au-benefice-d-unicef
- type: directory
  path: _clubs
  label: Clubs
  create: documents
  match: "**/*"
  templates:
  - club
- type: directory
  path: _actions
  label: Actions
  create: documents
  match: "**/*"
  templates:
  - don-pour-actions-for-life-project
upload_dir: assets/media
public_path: "/assets/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
