---
new_page_extension: md
auto_deploy: true
admin_path: "/admin/"
webhook_url: 
collections:
- path: __posts
  label: " posts"
  create: all
- path: _posts
  label: Posts
  create: all
- path: _events
  label: Events
  create: all
- path: _clubs
  label: Clubs
  create: all
- path: _actions
  label: Actions
  create: all
- path: ''
  label: Pages
  create: all
upload_dir: assets/media
public_path: "/assets/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
