---
new_page_extension: md
auto_deploy: true
admin_path: "/admin/"
webhook_url: 
sections:
- type: directory
  path: _events
  label: Events
  create: all
  match: "**/*"
- type: directory
  path: _clubs
  label: Clubs
  create: all
  match: "**/*"
- type: directory
  path: _actions
  label: Actions
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: assets/media
public_path: "/assets/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
