---
new_page_extension: md
auto_deploy: true
admin_path: "/admin/"
webhook_url: 
collections: 
upload_dir: assets/media
public_path: "/assets/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
