---
hide_body: true
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- type: select
  name: who
  config:
    source:
      type: pages
      section: clubs
  label: Club
- name: photo
  label: Photo
  type: file
  hidden: false
  default: ''
- type: textarea
  name: detail
  label: Détail
  config:
    wysiwyg: true
    schema:
      format: markdown
